account/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
__author__ = 'ChukovNA'

from django.conf.urls import patterns, url

from account import views

urlpatterns = patterns('',
                       url(r'^login/$', views.login, name='login'),
                       url(r'^logout/$', views.logout, name='logout'),
)

lisa_django/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'lisa_django.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('account.urls', namespace="account")),
    url(r'^reports/', include('reports.urls', namespace="reports")),
    url(r'^$', 'reports.views.index', name='index'),
)

reports/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
__author__ = 'ChukovNA'
from django.conf.urls import patterns, url

from reports import views

urlpatterns = patterns('',

                       url(r'$', views.index, name='index'), #this record mast be last!!!!
)

account/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    phone = models.CharField(max_length=30, blank=True)
    job = models.CharField(max_length=84, blank=True)
    department = models.CharField(max_length=30, blank=True)

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'


def user_post_save(sender, instance, **kwargs):
    ( profile, new ) = UserProfile.objects.get_or_create(user=instance)


models.signals.post_save.connect(user_post_save, sender=User)

reports/models.py
from django.db import models

# Create your models here.

account/views.py
from django.shortcuts import render_to_response, redirect
from django.contrib import auth
from django.core.context_processors import csrf
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from hashlib import md5
import logging
import traceback
import cx_Oracle
from django.conf import settings


def db_auth(username, password):
    logger = logging.getLogger(__name__)

    if username and password:
        try:
            dsn_tns = cx_Oracle.makedsn(settings.DATABASES['default']['HOST'], settings.DATABASES['default']['PORT'], settings.DATABASES['default']['NAME'])
            con = cx_Oracle.connect(username, password[::-1], dsn_tns)
            cursor = con.cursor()
            cursor.execute("set role lisaro identified by lisaro")
            cursor.execute("SELECT username,lastname,firstname,middlename,phone,email,job FROM lisa.usr_django_auth WHERE username=user")
            row = cursor.fetchone()
            if row:
                return dict(zip([x[0] for x in cursor.description], row))
            else:
                logger.info('Пользователь %s существует, но не имеет доступа к системе' % username)
        except cx_Oracle.DatabaseError as e:
            if e.args[0].code == 1017:
                pass
            else:
                logger.critical('Database connection error: ORA-%05d' % e.args[0].code)
        except:
            logger.error(traceback.format_exc())
            return False


class LisaBackend(object):
    def authenticate(self, username=None, password=None):
        logger = logging.getLogger(__name__)
        try:
            lisa_user = db_auth(username=username, password=password)

            if lisa_user:
                try:
                    logger.info('Пользователь %s авторизован в LISA (%s)' % (username, md5(password.encode('utf-8')).hexdigest().upper()))
                    user = User.objects.get(username=username,is_active=True)
                    logger.info('Пользователь найден (ID=%d)' % user.pk)
                    user.userprofile.phone = lisa_user['PHONE']
                    user.userprofile.job = lisa_user['JOB']
                    user.userprofile.save()
                    logger.info('Профиль пользователя обновлен')
                    return user
                except User.DoesNotExist:
                    user = User(username=username,
                                first_name=lisa_user['FIRSTNAME'],
                                last_name=lisa_user['LASTNAME'],
                                email=lisa_user['EMAIL'])
                    user.save()
                    logger.info('Пользователь создан (ID=%d)' % user.pk)
                    user.userprofile.phone = lisa_user['PHONE']
                    user.userprofile.job = lisa_user['JOB']
                    user.userprofile.save()
                    logger.info('Профиль пользователя создан (ID=%d)' % user.userprofile.pk)
                    return user
            else:
                logger.info('Пользователь %s НЕ авторизован в LISA (%s)' % (username, md5(password.encode('utf-8')).hexdigest().upper()))

        except Exception:
            logger.error(traceback.format_exc())

    def get_user(self, user_id):
        try:
            return User.objects.get(pk=user_id)
        except User.DoesNotExist:
            return None


def login(request):
    logger = logging.getLogger(__name__)

    args = {}
    args.update(csrf(request))
    if request.POST:
        username = request.POST.get('username', '').upper()
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            logger.info('Пользователь %s вошел в систему' % user.username)
            return redirect(reverse('reports:index'))
        else:

            return render_to_response('login.html', args)
    else:
        return render_to_response('login.html', args)


def logout(request):
    logger = logging.getLogger(__name__)
    logger.info('Пользователь %s вышел из системы' % request.user.username)
    auth.logout(request)
    return redirect(reverse('account:login'))

reports/views.py
from django.shortcuts import render, render_to_response
from django.contrib.auth.decorators import login_required
import logging

from django.conf import settings


@login_required
def index(request):
    logger = logging.getLogger(__name__)
    logger.debug(settings.LOGIN_URL)
    return render(request,'index.html')

account/templates/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Bootstrap Admin Theme</title>


{% include "css.html" %}




</head>

<body>
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Please Sign In</h3>
                </div>
                <div class="panel-body">
                    <form action="{% url 'account:login'%}" method="post" class="form-signin" role="form">
                        {% csrf_token %}
                        <fieldset>
                            <div class="form-group">
                                <input class="form-control" placeholder="Username" name="username" id="username" type="text" autofocus>
                            </div>
                            <div class="form-group">
                                <input class="form-control" placeholder="Password" name="password" id="password" type="password" value="">
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input name="remember" type="checkbox" value="Remember Me">Remember Me
                                </label>
                            </div>
                            <!-- Change this to a button or input when using this as a form -->
                            <!--<a type="submit" class="btn btn-lg btn-success btn-block">Login</a>-->

                            <button class="btn btn-lg btn-primary btn-block" type="submit">Войти</button>

                        </fieldset>

                        {% if login_error %}
                        <div class="alert alert-danger" role="alert">
                            <p class="text-center">{{ login_error }}</p>
                        </div>
                        {% endif %}


                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% include "js.html" %}

</body>

</html>

reports/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Lisa reports</title>


{% include "css.html" %}


</head>

<body>

<div id="wrapper">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="index.html">LISA REPORTS v0.0</a>
        </div>
        <!-- /.navbar-header -->
        <ul class="nav navbar-top-links navbar-right">
            <!-- /.dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i> {{ user.first_name }} {{ user.last_name }} <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                    </li>
                    <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                    </li>
                    <li class="divider"></li>
                    <li><a href="{% url 'account:logout' %}"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                    </li>
                </ul>
                <!-- /.dropdown-user -->
            </li>
            <!-- /.dropdown -->
        </ul>
        <!-- /.navbar-top-links -->

        <div class="navbar-default sidebar side-menu" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">

                    <li>
                        <a href="index.html"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                    </li>


                    <li>
                        <a href="tables.html"><i class="fa fa-table fa-fw"></i> Tables</a>
                    </li>


                                        <li class="">
                        <a href="#"><i class="fa fa-files-o fa-fw"></i>Администрирование<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level collapse" aria-expanded="false" style="height: 0px;">
                            <li>
                                <a href="{% url 'admin:index' %}">Пользователи</a>
                            </li>
                        </ul>
                        <!-- /.nav-second-level -->
                    </li>



                    <li class="">
                        <a href="#"><i class="fa fa-files-o fa-fw"></i> Sample Pages<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level collapse" aria-expanded="false" style="height: 0px;">
                            <li>
                                <a href="blank.html">Blank Page</a>
                            </li>
                            <li>
                                <a href="login.html">Login Page</a>
                            </li>
                        </ul>
                        <!-- /.nav-second-level -->
                    </li>


                </ul>
            </div>
            <!-- /.sidebar-collapse -->
        </div>
        <!-- /.navbar-static-side -->
    </nav>

    <!-- Page Content -->
    <div id="page-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Blank</h1>


                    {% if user.is_authenticated %}
                        <p>Welcome, {{ user.first_name }} {{ user.last_name }}. Thanks for logging in.</p>
                    {% else %}
                        <p>Welcome, new user. Please log in.</p>
                    {% endif %}


                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /#page-wrapper -->

</div>

{% include "js.html" %}

</body>

</html>

templates/css.html
{% load staticfiles %}
<!-- CSS declaration django static incusion -->
<!-- Bootstrap Core CSS -->
<link href="{% static 'dist/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<!-- MetisMenu CSS -->
<link href="{% static 'dist/metisMenu/css/metisMenu.min.css' %}" rel="stylesheet">
<!-- Custom CSS -->
<link href="{% static 'dist/custom/css/sb-admin-2.css'%}" rel="stylesheet">
<!-- Custom Fonts -->
<link href="{% static 'dist/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

templates/js.html
{% load staticfiles %}
<!-- JS declaration django static incusion -->
<!-- jQuery -->
<script src="{% static 'dist/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap Core JavaScript -->
<script src="{% static 'dist/bootstrap/js/bootstrap.min.js' %}"></script>
<!-- Metis Menu Plugin JavaScript -->
<script src="{% static 'dist/metisMenu/js/metisMenu.min.js' %}"></script>
<!-- Custom Theme JavaScript -->
<script src="{% static 'dist/custom/js/sb-admin-2.js' %}"></script>